### ISSUE TITLE
pawn promotion

### ISSUE THREAD

**Issue by j7zd** [Al1002/Chess#7]
the board has space on the top and bottom for a pop up selection buttons to be for the selection of piece to promote to

need to edit view.py to visualize it
edit input to detect those inputs outside

**Comment by Al1002** [comment]
Added promotion in main branch, missing implementation for self.draw.promotion(player)

**Comment by Al1002** [comment]
Added draw.promotion, please fix alignment

**Comment by j7zd** [comment]
fixed alingment
